//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_number
    {
        public int contact_number_id { get; set; }
        public string contact_number1 { get; set; }
        public int account_id { get; set; }
    
        public virtual account account { get; set; }
    }
}
